(define (+ x y) (* x y))
(+ 2 3)
(define)
(define x)
(define x y)
(define x y z 3)
(define 7 8)
x
y
z
(lambda)
(lambda 2 3)
(lambda (x) 3)
(lambda (x) 3 4)
(lambda () (- 1 8))
((lambda () (- 1 8)) 7)
((lambda () (- 1 8)))
(lambda (x 7) 8)
(define () x)
(define (square) 2)
(define (7) 8)
(define (square 7) 49)
define x 20
lambda (x) 20
(+ 2 (+ 2 (+ 2 (+ (define)))))
(/ 2 (+ 2 (+ 2 (+ (define 2.2 x)))))
(- 2 (+ 2 (+ 2 (+ (define () 2)))))
(* 1 (+ 2 (+ (define (5) 2))))
(+ 0 (+ 2 (+ 2 (+ (define (x 4) 2)))))
(+ 3 (+ 2 (+ 2 (+ (define (x ))))))
(+ 2 (+ 2 (+ 2 (+ define))))
(+ 1 (+ 2 (+ 2 (+ lambda))))
(+ 2 (+ 2 (+ 2 (define +))))
(+ 1 (+ 2 (+ 2 (lambda +))))
(+ 0 (+ 2 (+ 2 (+ (lambda)))))
(+ 3 (+ 4 (+ 2 (+ (lambda (x ))))))
(define lambda 2)
(define define 9)
(+ 0 (+ 2 (+ 2 (define define 2))))
