(length (list 9 8 7 6))
(length (list (list 7 8 9)))
(length (list))
(length 7)
(length (cons 1 2))
(length ())
(length (cdr (cdr (list 1 2))))
(length x)
(length () x)
(length () ())
(length)
(length (cons 1 (cons 2 3)))
