(append (list 1) (list 2) (list 3) (list 4))
(append (list 5) (list) (list 6) () (list 7))
(append (list 9 8 7))
(append (list 1) (list 2 3 4 5 9 10))
(append (list 1) (list 2) (list 3))
(append)
(append (append) (list 1))
(append (list 1) (append))
(define x (list 1))
(append x x x)
x
(append 7 8 9)
(append (cons 1 2) (cons 3 4))
(define x (list 1 2 3))
(define y (list 9 8 7))
(append x y x y)
x
y
(append () (list) (cdr (list 1)))
(append 0)
(append #f)
(append #t)
(append (list 1) 0)
(append (list #t) #f)
(append (list #f) #t)
(append (list 1) (list 0))
